In [805]:
import numpy as np 
import math

In [806]:
def relu(input):
    if input > 0:
        return input
    else:
        return 0

In [807]:
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [808]:
x1 = np.array([0,0])
x2 = np.array([0,1])
x3 = np.array([1,0])
x4 = np.array([1,1])
y = np.array([0,1,1,0])
y1 = 0
y2 = 1
y3 = 1
y4 = 0
w = np.array([[0.79,0.87],[1.34,1.08]])
b = np.array([0.1,-1.12])
wy = np.array([0.68,-2.01])
by = -0.3

In [809]:
def forward(weights, bias,weight_y, bias_y,x):
    a1 = bias[0] + np.dot(weights[0],x)
    a2 = bias[1] + np.dot(weights[1],x)
    h1 = relu(a1)
    h2 = relu(a2)
    a3 = by + np.dot(wy,np.array([h1,h2]))
    y = sigmoid(a3)
    return y, a1, a2, a3, h1, h2

In [810]:
yh = np.array([])
for i in [x1,x2,x3,x4]:
    yh = np.append(yh,forward(w,b,wy,by,i)[0])
    print(forward(w,b,wy,by,i))
print(yh)

(0.44225875669051, 0.1, -1.12, -0.23199999999999998, 0.1, 0)
(0.5889436018907238, 0.97, -0.040000000000000036, 0.3596000000000001, 0.97, 0)
(0.465803469499505, 0.89, 0.21999999999999997, -0.13699999999999984, 0.89, 0.21999999999999997)
(0.1523612754212008, 1.7600000000000002, 1.2999999999999998, -1.7161999999999993, 1.7600000000000002, 1.2999999999999998)
[0.44225876 0.5889436  0.46580347 0.15236128]


In [811]:
def cross_entropy_loss(y,y_hat):
    sum = 0
    for i in range(len(y_hat)):
        sum -= (y[i] * math.log(y_hat[i])) + ((1-y[i])* math.log(1-y_hat[i]))
    return sum

In [812]:
print(y)
print(yh)

[0 1 1 0]
[0.44225876 0.5889436  0.46580347 0.15236128]


In [813]:
print(cross_entropy_loss(y,yh))

2.042577237432488


# Question 4

In [814]:
def transfer_derivative(output):
	return output * (1.0 - output)

print(transfer_derivative(0.4658))

0.24883036


In [815]:
def relu_der(input):
    if input >= 0:
        return 1
    if input < 0:
        return 0

# Question 5

In [816]:
y_hat, a1, a2, a3, h1, h2 = forward(w,b,wy,by,x3)
J_yhat = -1/y_hat
g = J_yhat
J_a3 = g * transfer_derivative(a3)
g = J_a3
J_bk = g 
J_wk = np.dot(g,np.array([h1,h2]).T)
G_hk = np.dot(np.array(wy).T,g)
g = G_hk

In [817]:
J_a1a2 = np.multiply(g,np.array([relu_der(a1), relu(a2)]).T)
g = J_a1a2
J_b1 = g
J_w11w12 = np.dot(g[0],x3)
J_w13w14 = np.dot(g[1],x3)
print(J_a1a2)
print(J_w11w12)
print(J_w13w14)

[ 0.19828455 -0.12894328]
[0.19828455 0.        ]
[-0.12894328  0.        ]


In [818]:
n = 0.2
wy = wy - np.dot(n,J_wk)
by = by - n*J_bk
w1 = w - np.dot(n,np.array([J_w11w12, J_w13w14]))
b1 = b - np.dot(n,J_b1)

In [819]:
print(wy)
print(by)
print(w1)
print(b1)

[ 0.6280961  -2.02283018]
-0.3583189860308744
[[0.75034309 0.87      ]
 [1.36578866 1.08      ]]
[ 0.06034309 -1.09421134]


In [820]:
yh = np.array([])
for i in [x1,x2,x3,x4]:
    y_hat, a1, a2, a3, h1, h2 = forward(w1,b1,wy,by,i)
    #print(forward(w,b,wy,by,i))
    print(h1,h2)
    yh = np.append(yh,y_hat)
print(yh)

0.06034308949900538 0
0.9303430894990053 0
0.8106861789980108 0.27157731124570517
1.6806861789980108 1.3515773112457052
[0.42057395 0.55626713 0.4016764  0.1154034 ]


In [821]:
print(cross_entropy_loss(y,yh))

2.1669559196840993
